### ISSUE TITLE
Before submission...

### ISSUE THREAD

**Issue by nhcooper123** [nhcooper123/time-slice#14]
- [x] packrat all packages including disparity/release dispRity
- [x] checkpoint the date
- [x] reinstall all packages, inc dispRity and Claddis
- [x] rerun all analyses and figures 
- [x] get system info for README

**Comment by nhcooper123** [comment]
I can't get packrat to work so we will just have to use checkpoint and syst info

**Comment by TGuillerme** [comment]
OK, I've just pushed the release of `dispRity v0.5` on the `"release"` branch. This is going to be the version I will resubmit so It'll probably won't change for a while.

For repeatability, you can directly link to the tag 0.5:

```{r}
install_github("TGuillerme/dispRity@v0.5")
```
