### ISSUE TITLE
Questions for Thomas in the writing

### ISSUE THREAD

**Issue by nhcooper123** [nhcooper123/time-slice#15]
I'll make tick boxes so you can tick them off when you've done them, maybe provide me the answers below?

EASY
- [x] In the ``gradual splits'' bit. I'm unsure what you mean by "the distance between the slice." Do you mean the branch length, the interval between slices, or the distance between the slice and the node? Also you define d(x,y) but d(x,y) doesn't appear in the equations.
- [x] Did we Bonferonni the extinction wilcoxons?

HARD(ER)
- [x] Can you add references throughout for me? Mostly needed in the intro. You're more familiar with the literature so I figured you could do this really quickly where it might take me ages. And check any references I've inserted. I went for a bit of a random approach!
- [x] Check the methods to check I've not changed anything vital!
- [x] Check the results make sense
- [x] Check the intro makes sense

**Comment by TGuillerme** [comment]
EASY:
- Yes extinction tests are bonferonnied.

**Comment by TGuillerme** [comment]
Hard(er) points dealt with in commits pm the manuscript from Friday the 15th.
