### ISSUE TITLE
Check through all code for comments and tidiness and functionality!!!

### ISSUE THREAD

**Issue by nhcooper123** [nhcooper123/time-slice#17]
Check comments etc.
- [x] 01 
- [x] 02 
- [x] 03 
- [x] 04 
- [x] 05 
- [x] 06 
- [x] 07 
- [x] 08 
- [x] 09
- [x] 10
- [x] 11 
- [x] 12

**Comment by TGuillerme** [comment]
I've test codes 01, 02, 08 and 09. All good. In 03, I've tested the extinction bit (now only on two datasets).

The next ones will work on the right data.

If you go through checking the comments, it's worth adding a disclaimer that `02` takes some time (>30 minutes).

**Comment by nhcooper123** [comment]
OK cool. Currently in the process of rerunning everything as one last check.

**Comment by nhcooper123** [comment]
New version of tidyverse breaks 06. But I already had the tables so can submit and sort later
