### ISSUE TITLE
New figure edits

### ISSUE THREAD

**Issue by nhcooper123** [nhcooper123/time-slice#28]
- [x] Can we us N rather than n? I think that matches the rest of the paper
- [x] rather than : can we use =
- [x] instead of N bins, it should be N bins/slices =
- [x] instead of bins length, it should be size/interval =
- [x] needs to be MY NOT MYa (as it's million years not million years ago)
- [x] the file name needs to be Figure2-binning.pdf (or similar but needs Figure2 in it )

These should all be fairly quick to change. 🐙

**Comment by TGuillerme** [comment]
Done :aerial_tramway:
